<?php

/**
 * This is the model base class for the table "vdc_user_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserStatus".
 *
 * Columns in table "vdc_user_status" available as properties of the model,
 * followed by relations of table "vdc_user_status" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $key
 *
 * @property Profiles[] $profiles
 */
abstract class BaseUserStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_user_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserStatus|UserStatuses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, key', 'required'),
			array('name, key', 'length', 'max'=>30),
			array('id, name, key', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'profiles' => array(self::HAS_MANY, 'Profiles', 'user_status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'key' => Yii::t('app', 'Key'),
			'profiles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('key', $this->key, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}