<?php

/**
 * This is the model base class for the table "vdc_order_status_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderStatusHistory".
 *
 * Columns in table "vdc_order_status_history" available as properties of the model,
 * followed by relations of table "vdc_order_status_history" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_id
 * @property string $change_date
 * @property integer $order_status_id
 *
 * @property Order $order
 * @property OrderStatus $orderStatus
 */
abstract class BaseOrderStatusHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_order_status_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderStatusHistory|OrderStatusHistories', $n);
	}

	public static function representingColumn() {
		return 'change_date';
	}

	public function rules() {
		return array(
			array('order_id, change_date, order_status_id', 'required'),
			array('order_id, order_status_id', 'numerical', 'integerOnly'=>true),
			array('id, order_id, change_date, order_status_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'order' => array(self::BELONGS_TO, 'Order', 'order_id'),
			'orderStatus' => array(self::BELONGS_TO, 'OrderStatus', 'order_status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => null,
			'change_date' => Yii::t('app', 'Change Date'),
			'order_status_id' => null,
			'order' => null,
			'orderStatus' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('change_date', $this->change_date, true);
		$criteria->compare('order_status_id', $this->order_status_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}