<?php

/**
 * This is the model base class for the table "vdc_payment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Payment".
 *
 * Columns in table "vdc_payment" available as properties of the model,
 * followed by relations of table "vdc_payment" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_id
 * @property string $create_date
 * @property integer $designer_price
 * @property integer $client_price
 * @property integer $debt
 *
 * @property Order $order
 * @property PaymentHistory[] $paymentHistories
 */
abstract class BasePayment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_payment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Payment|Payments', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('order_id, create_date, designer_price, client_price, debt', 'required'),
			array('order_id, designer_price, client_price, debt', 'numerical', 'integerOnly'=>true),
			array('id, order_id, create_date, designer_price, client_price, debt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'order' => array(self::BELONGS_TO, 'Order', 'order_id'),
			'paymentHistories' => array(self::HAS_MANY, 'PaymentHistory', 'payment_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => null,
			'create_date' => Yii::t('app', 'Create Date'),
			'designer_price' => Yii::t('app', 'Designer Price'),
			'client_price' => Yii::t('app', 'Client Price'),
			'debt' => Yii::t('app', 'Debt'),
			'order' => null,
			'paymentHistories' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('designer_price', $this->designer_price);
		$criteria->compare('client_price', $this->client_price);
		$criteria->compare('debt', $this->debt);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}