<?php

/**
 * This is the model base class for the table "vdc_document".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Document".
 *
 * Columns in table "vdc_document" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $filename
 * @property integer $admin
 * @property integer $designer
 * @property integer $manager
 * @property integer $disabled
 *
 */
abstract class BaseDocument extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_document';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Document|Documents', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('filename', 'required'),
			array('admin, designer, manager, disabled', 'numerical', 'integerOnly'=>true),
			array('name, filename', 'length', 'max'=>200),
			array('name, admin, designer, manager, disabled', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, filename, admin, designer, manager, disabled', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'filename' => Yii::t('app', 'Filename'),
			'admin' => Yii::t('app', 'Admin'),
			'designer' => Yii::t('app', 'Designer'),
			'manager' => Yii::t('app', 'Manager'),
			'disabled' => Yii::t('app', 'Disabled'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('filename', $this->filename, true);
		$criteria->compare('admin', $this->admin);
		$criteria->compare('designer', $this->designer);
		$criteria->compare('manager', $this->manager);
		$criteria->compare('disabled', $this->disabled);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}