<?php

/**
 * This is the model base class for the table "vdc_AuthAssignment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AuthAssignment".
 *
 * Columns in table "vdc_AuthAssignment" available as properties of the model,
 * followed by relations of table "vdc_AuthAssignment" available as properties of the model.
 *
 * @property integer $id
 * @property string $itemname
 * @property integer $userid
 * @property string $bizrule
 * @property string $data
 *
 * @property AuthItem $itemname0
 * @property User $user
 */
abstract class BaseAuthAssignment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_AuthAssignment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AuthAssignment|AuthAssignments', $n);
	}

	public static function representingColumn() {
		return 'itemname';
	}

	public function rules() {
		return array(
			array('itemname, userid', 'required'),
			array('userid', 'numerical', 'integerOnly'=>true),
			array('itemname', 'length', 'max'=>64),
			array('bizrule, data', 'safe'),
			array('bizrule, data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, itemname, userid, bizrule, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'itemname0' => array(self::BELONGS_TO, 'AuthItem', 'itemname'),
			'user' => array(self::BELONGS_TO, 'User', 'userid'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'itemname' => null,
			'userid' => null,
			'bizrule' => Yii::t('app', 'Bizrule'),
			'data' => Yii::t('app', 'Data'),
			'itemname0' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('itemname', $this->itemname);
		$criteria->compare('userid', $this->userid);
		$criteria->compare('bizrule', $this->bizrule, true);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}