<?php

/**
 * This is the model base class for the table "vdc_variables".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Variables".
 *
 * Columns in table "vdc_variables" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $max_global_number
 * @property integer $prev_designer_id
 * @property string $vdc_info
 *
 */
abstract class BaseVariables extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_variables';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Variables|Variables', $n);
	}

	public static function representingColumn() {
		return 'vdc_info';
	}

	public function rules() {
		return array(
			array('max_global_number, prev_designer_id, vdc_info', 'required'),
			array('max_global_number, prev_designer_id', 'numerical', 'integerOnly'=>true),
			array('id, max_global_number, prev_designer_id, vdc_info', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'max_global_number' => Yii::t('app', 'Max Global Number'),
			'prev_designer_id' => Yii::t('app', 'Prev Designer'),
			'vdc_info' => Yii::t('app', 'Vdc Info'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('max_global_number', $this->max_global_number);
		$criteria->compare('prev_designer_id', $this->prev_designer_id);
		$criteria->compare('vdc_info', $this->vdc_info, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}