<?php

/**
 * This is the model base class for the table "vdc_payment_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PaymentHistory".
 *
 * Columns in table "vdc_payment_history" available as properties of the model,
 * followed by relations of table "vdc_payment_history" available as properties of the model.
 *
 * @property integer $id
 * @property integer $payment_id
 * @property string $create_date
 * @property integer $amount
 *
 * @property Payment $payment
 */
abstract class BasePaymentHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_payment_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PaymentHistory|PaymentHistories', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('payment_id, create_date, amount', 'required'),
			array('payment_id, amount', 'numerical', 'integerOnly'=>true),
			array('id, payment_id, create_date, amount', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'payment' => array(self::BELONGS_TO, 'Payment', 'payment_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'payment_id' => null,
			'create_date' => Yii::t('app', 'Create Date'),
			'amount' => Yii::t('app', 'Amount'),
			'payment' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('payment_id', $this->payment_id);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('amount', $this->amount);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}