<?php

/**
 * This is the model base class for the table "vdc_order_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderType".
 *
 * Columns in table "vdc_order_type" available as properties of the model,
 * followed by relations of table "vdc_order_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $disabled
 *
 * @property Order[] $orders
 * @property Price[] $prices
 */
abstract class BaseOrderType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_order_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderType|OrderTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('disabled', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('disabled', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, disabled', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'orders' => array(self::HAS_MANY, 'Order', 'order_type_id'),
			'prices' => array(self::HAS_MANY, 'Price', 'order_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'disabled' => Yii::t('app', 'Disabled'),
			'orders' => null,
			'prices' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('disabled', $this->disabled);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}