<?php

/**
 * This is the model base class for the table "vdc_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "vdc_user" available as properties of the model,
 * followed by relations of table "vdc_user" available as properties of the model.
 *
 * @property integer $id
 * @property string $login
 * @property string $password
 * @property string $email
 *
 * @property Designer[] $designers
 * @property Manager[] $managers
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vdc_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'login';
	}

	public function rules() {
		return array(
			array('login, password, email', 'required'),
			array('login, password, email', 'length', 'max'=>100),
			array('id, login, password, email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'designers' => array(self::HAS_MANY, 'Designer', 'user_id'),
			'managers' => array(self::HAS_MANY, 'Manager', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'login' => Yii::t('app', 'Login'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'designers' => null,
			'managers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('login', $this->login, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}